// Single source of truth for design tokens.
//
// Parses the :root block of src/app/globals.css and emits a typed union of
// every CSS custom-property name into src/types/tokens.ts, plus a cssVar()
// helper. Components type their token references against this union, so a typo
// like cssVar('accent-greeen') fails `tsc`. The committed output is verified in
// CI (`npm run tokens:check`): edit globals.css, regenerate, commit — never the
// other way around.
//
// Usage: node scripts/gen-tokens.mjs   (or `npm run tokens:gen`)

import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const cssPath = join(root, 'src', 'app', 'globals.css');
const outPath = join(root, 'src', 'types', 'tokens.ts');

const css = readFileSync(cssPath, 'utf8');

// Extract the flat declaration list inside the first `:root { … }` block.
const open = css.indexOf(':root {');
if (open === -1) throw new Error('gen-tokens: `:root {` block not found in globals.css');
const close = css.indexOf('}', open);
const rootBlock = css.slice(open, close);

const names = [...new Set([...rootBlock.matchAll(/--([\w-]+)\s*:/g)].map((m) => m[1]))].sort();

const banner = '// AUTO-GENERATED by scripts/gen-tokens.mjs — do not edit by hand.\n// Run `npm run tokens:gen` after changing tokens in src/app/globals.css.\n';

const body = `${banner}
/** Every design token declared in the \`:root\` block of globals.css. */
export const CSS_TOKENS = [
${names.map((n) => `  '${n}',`).join('\n')}
] as const;

export type CssToken = (typeof CSS_TOKENS)[number];

/** Type-checked \`var(--token)\` reference. A misspelled token fails to compile. */
export function cssVar(token: CssToken): string {
  return \`var(--\${token})\`;
}
`;

writeFileSync(outPath, body);
console.log(`gen-tokens: wrote ${names.length} tokens to src/types/tokens.ts`);
